import esbuild from "esbuild";
import fs from "fs";
import process from "process";
import builtins from "builtin-modules";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

function patchImportMetaUrl() {
  const bundlePath = "main.js";
  const source = fs.readFileSync(bundlePath, "utf8");
  const patched = source.replace(
    "var import_meta = {};",
    'var import_meta = { url: require("url").pathToFileURL(__filename).href };'
  );
  if (patched !== source) {
    fs.writeFileSync(bundlePath, patched);
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  loader: { ".md": "text" },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
});

if (prod) {
  await context.rebuild();
  patchImportMetaUrl();
  process.exit(0);
} else {
  await context.watch();
}
